;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anchored-transpose
        ar/set-mc/insert-numbers-starting-value
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-slash
        c-indent-line-or-region
        comment-line
        electric-newline-and-maybe-indent
        eval-and-replace
        forward-sexp
        indent-for-tab-command
        kill-region
        mark-sexp
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        org-ctrl-c-minus
        org-cycle
        org-force-self-insert
        org-kill-line
        org-return-and-maybe-indent
        org-self-insert-command
        org-yank
        py-electric-comment
        smart-hungry-delete-backward-char
        smart-hungry-delete-forward-char
        tab-to-tab-stop
        vr/query-replace
        wdired--self-insert
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        iedit-switch-to-mc-mode
        kmacro-end-or-call-macro
        org-export-dispatch
        wdired-finish-edit
        x-hydra/body
        ))
